#!/usr/bin/env bash
#
# build-claude-config.sh
# Builds ~/.claude/CLAUDE.md by merging personal and work configurations
#
# This script is safe to run multiple times (idempotent)
#

set -euo pipefail

# Determine the dotfiles directory
DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
CLAUDE_DIR="$HOME/.claude"
WORK_CLAUDE_DIR="${CLAUDE_WORK_DIR:-$HOME/.claude/work}"

# Source files
PERSONAL_CLAUDE="$DOTFILES_DIR/claude/personal/CLAUDE.md"
WORK_CLAUDE="$WORK_CLAUDE_DIR/CLAUDE.md"

# Destination
OUTPUT_FILE="$CLAUDE_DIR/CLAUDE.md"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔧 Building Claude configuration...${NC}"

# Ensure ~/.claude directory exists
mkdir -p "$CLAUDE_DIR"

# Check if personal config exists
if [[ ! -f "$PERSONAL_CLAUDE" ]]; then
    echo -e "${RED}❌ Error: Personal CLAUDE.md not found at $PERSONAL_CLAUDE${NC}"
    exit 1
fi

# Start building the output file
{
    echo "<!-- Generated by $DOTFILES_DIR/claude/build-claude-config.sh -->"
    echo "<!-- DO NOT EDIT THIS FILE DIRECTLY -->"
    echo "<!-- Edit source files and run: make claude-config -->"
    echo ""

    # Include personal configuration
    cat "$PERSONAL_CLAUDE"

    # Check if work configuration exists
    if [[ -f "$WORK_CLAUDE" ]]; then
        echo ""
        echo "---"
        echo ""
        echo "# Work Configuration"
        echo ""
        echo "<!-- Merged from $WORK_CLAUDE -->"
        echo ""
        cat "$WORK_CLAUDE"
        echo -e "${GREEN}✓ Merged work configuration from $WORK_CLAUDE${NC}"
    else
        echo -e "${YELLOW}⚠ No work configuration found at $WORK_CLAUDE (skipping)${NC}"
    fi

} > "$OUTPUT_FILE"

echo -e "${GREEN}✅ Generated $OUTPUT_FILE${NC}"

# Show a summary
PERSONAL_LINES=$(wc -l < "$PERSONAL_CLAUDE")
TOTAL_LINES=$(wc -l < "$OUTPUT_FILE")
WORK_LINES=$((TOTAL_LINES - PERSONAL_LINES - 10)) # Approximate, accounting for headers

echo ""
echo "📊 Summary:"
echo "  Personal config: $PERSONAL_LINES lines"
if [[ -f "$WORK_CLAUDE" ]]; then
    echo "  Work config:     $WORK_LINES lines (approx)"
fi
echo "  Total:           $TOTAL_LINES lines"
echo ""
echo -e "${BLUE}💡 Tip: Run 'make claude-config' to rebuild anytime${NC}"
