shell = "zsh -c '{}'"
preferred-schemes = ["base16-gruvbox-material-dark-hard", "base24-github-dark"]

hooks = ["osascript -so ~/.dotfiles/dot-config/ghostty/reload-config.scpt"]

[[items]]
name = "tmux"
path = "https://github.com/tinted-theming/tinted-tmux"
themes-dir = "colors"
hook = "tmux run 2> /dev/null && tmux source-file %f"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-delta"
name = "delta"
themes-dir = "configs"
hook = "cp -f %f ~/.config/tinted-theming/delta.gitconfig"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-fzf"
name = "fzf"
themes-dir = "sh"
hook = "cp -f %f ~/.config/tinted-theming/fzf.sh"
supported-systems = ["base16", "base24"]


[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal-ghostty"
themes-dir = "themes/ghostty-scripts"
hook = '''
sh %f \
    -g 12 \
    -s 12 \
    >! ~/.config/ghostty/themes/tinted-theming
'''
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal-alacritty"
themes-dir = "themes/alacritty"
hook = "cp -f %f ~/.config/alacritty/colors.toml && touch ~/.config/alacritty/alacritty.toml"
supported-systems = ["base16", "base24"]

# [[items]]
# path = "https://github.com/tinted-theming/tinted-terminal"
# name = "tinted-terminal-iterm2"
# # revision = "8996a7d799e90f447df973d3d8f1901b4bab0e52"
# themes-dir = "themes-16/iterm2-scripts"
# hook = "sh %f"
# supported-systems = ["base16", "base24"]
