# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
#
gui:
  nerdFontsVersion: '3'
os:
  open: 'open {{filename}}'
keybinding:
  universal:
    quit: 'Q'
git:
  mainBranches: ['master', 'main', 'live']
