# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
#
gui:
  nerdFontsVersion: '3'
os:
  open: 'open {{filename}}'
keybinding:
  universal:
    quit: 'Q'
git:
  mainBranches: ['master', 'main', 'live']
customCommands:
  - key: '<c-t>'
    context: global
    description: 'Open Lazygit in new tmux window'
    command: '[[ -n $TMUX ]] && tmux new-window -c $(tmux display-message -p "#{pane_current_path}") lazygit && tmux display-popup -C'

