# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/v0.42.0/schema/config.json
#
# Configuration Reference: https://github.com/jesseduffield/lazygit/blob/v0.42.0/docs/Config.md
gui:
  nerdFontsVersion: '3'
  expandFocusedSidePanel: true
  showBottomLine: false
  theme:
    selectedLineBgColor:
      - reverse
  # Spinner config will be respected by a future LazyGit release
  spinner:
    frames: ['⠋ ', '⠙ ', '⠹ ', '⠸ ', '⠼ ', '⠴ ', '⠦ ', '⠧ ', '⠇ ', '⠏ '] 
os:
  open: 'open {{filename}}'
  editPreset: "nvim"
keybinding:
  universal:
    quit: 'Q'
git:
  mainBranches: ['main', 'master', 'live']
  paging:
    colorArg: always
    pager: delta --paging=never --detect-dark-light=never
customCommands:
  - key: '<c-t>'
    context: global
    description: 'Open Lazygit in new tmux window'
    command: '[[ -n $TMUX ]] && tmux new-window -c $(tmux display-message -p "#{pane_current_path}") lazygit && tmux display-popup -C'
#promptToReturnFromSubprocess: false

