#!/usr/bin/env bash

brew install ack
brew install android-sdk
brew install ansiweather
brew install antigen
brew install archey
brew install augeas
brew install autoconf
brew install automake
brew install bison
brew install boot2docker
brew install brew-cask
brew install cabal-install
brew install cairo
brew install cmake
brew install cmatrix
brew install coreutils
brew install cowsay
brew install cscope
brew install ctags
brew install curl
brew install czmq
brew install dialog
brew install docker
brew install drafter
brew install emacs
brew install emacs-mac
brew install fasd
brew install ffmpeg
brew install figlet
brew install fish
brew install fontconfig
brew install fontforge
brew install fortune
brew install freetype
brew install fzf
brew install gdbm
brew install gettext
brew install ghc
brew install gifsicle
brew install gist
brew install git
brew install git-cal
brew install git-lfs
brew install glib
brew install gmp
brew install gnupg
brew install gnutls
brew install go
brew install gobject-introspection
brew install groovy
brew install gti
brew install harfbuzz
brew install htop-osx
brew install httpie
brew install hub
brew install icu4c
brew install imagemagick
brew install imgcat
brew install irssi
brew install jpeg
brew install jq
brew install keybase
brew install lame
brew install letsencrypt
brew install libcaca
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libpng
brew install libsodium
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libvo-aacenc
brew install libxml2
brew install libzip
brew install lua
brew install luajit
brew install macvim
brew install mcrypt
brew install mhash
brew install msgpack
brew install mysql
brew install ncdu
brew install neovim
brew install nettle
brew install ngrok
brew install node
brew install nvm
brew install oniguruma
brew install openssl
brew install pango
brew install pcre
brew install php56
brew install phpctags
brew install pixman
brew install pkg-config
brew install postgresql
brew install pyenv
brew install python
brew install python3
brew install rbenv
brew install re2c
brew install readline
brew install reattach-to-user-namespace
brew install ruby-build
brew install scons
brew install screenfetch
brew install sl
brew install smartmontools
brew install sqlite
brew install ssh-copy-id
brew install sshfs
brew install subliminal
brew install the_silver_searcher
brew install tldr
brew install tmux
brew install tree
brew install tty-clock
brew install unixodbc
brew install unrar
brew install weechat
brew install wemux
brew install wget
brew install x264
brew install xvid
brew install xz
brew install youtube-dl
brew install zeromq
brew install zsh
brew install zsh-completions
