
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]


[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"

[scrolling]
history = 100000

[font]
normal = { family = "BerkeleyMono Nerd Font Mono" }
bold = { family = "BerkeleyMono Nerd Font Mono" }
italic = { family = "BerkeleyMono Nerd Font Mono" }
bold_italic = { family = "BerkeleyMono Nerd Font Mono" }
size = 13
offset = { x = 0, y = 5 }

[general]
live_config_reload = true
import = ["~/.config/alacritty/colors.toml"]

[terminal]
