local gum_color_primary=
local gum_color_header_fg=13
local gum_color_selection=3

# `gum choose`
#
export GUM_CHOOSE_HEADER_BOLD=true
export GUM_CHOOSE_CURSOR_FOREGROUND=$gum_color_selection
# export GUM_CHOOSE_CURSOR_BACKGROUND=
export GUM_CHOOSE_HEADER_FOREGROUND=$gum_color_header_fg
export GUM_CHOOSE_ITEM_FOREGROUND=7
export GUM_CHOOSE_SELECTED_FOREGROUND=0
export GUM_CHOOSE_SELECTED_BACKGROUND=$gum_color_selection

# `gum input`
#
export GUM_INPUT_HEADER_BOLD=true
# export GUM_INPUT_PROMPT_FOREGROUND=
# export GUM_INPUT_PROMPT_BACKGROUND=
export GUM_INPUT_HEADER_FOREGROUND=$gum_color_header_fg
export GUM_INPUT_PLACEHOLDER_FOREGROUND=8
# export GUM_INPUT_PLACEHOLDER_BACKGROUND=
export GUM_INPUT_CURSOR_FOREGROUND=7
# export GUM_INPUT_CURSOR_BACKGROUND=


# `gum confirm`
#
export GUM_CONFIRM_HEADER_BOLD=true
export GUM_CONFIRM_PROMPT_FOREGROUND=$gum_color_header_fg
export GUM_CONFIRM_SELECTED_FOREGROUND=0
export GUM_CONFIRM_SELECTED_BACKGROUND=$gum_color_selection
# export GUM_CONFIRM_UNSELECTED_FOREGROUND=
# export GUM_CONFIRM_UNSELECTED_BACKGROUND=
#

# `gum confirm`
#
export GUM_CONFIRM_PROMPT_FOREGROUND=$gum_color_header_fg
export GUM_CONFIRM_SELECTED_FOREGROUND=0
export GUM_CONFIRM_SELECTED_BACKGROUND=$gum_color_selection
# export GUM_CONFIRM_UNSELECTED_FOREGROUND=
# export GUM_CONFIRM_UNSELECTED_BACKGROUND=

# `gum file`
export GUM_FILE_HEADER_BOLD=true
export GUM_FILE_CURSOR_FOREGROUND=$gum_color_selection
# export GUM_FILE_CURSOR_BACKGROUND=
# export GUM_FILE_SYMLINK_FOREGROUND=
# export GUM_FILE_SYMLINK_BACKGROUND=
export GUM_FILE_DIRECTORY_FOREGROUND=4
# export GUM_FILE_DIRECTORY_BACKGROUND=
# export GUM_FILE_FILE_FOREGROUND=
# export GUM_FILE_FILE_BACKGROUND=
# export GUM_FILE_PERMISSIONS_FOREGROUND=
# export GUM_FILE_PERMISSIONS_BACKGROUND=
export GUM_FILE_SELECTED_FOREGROUND=15
export GUM_FILE_SELECTED_BACKGROUND=19
# export GUM_FILE_FILE_SIZE_FOREGROUND=
# export GUM_FILE_FILE_SIZE_BACKGROUND=
export GUM_FILE_HEADER_FOREGROUND=$gum_color_header_fg
# export GUM_FILE_HEADER_BACKGROUND=


# `gum write`
#
export GUM_WRITE_HEADER_BOLD=true
# export GUM_WRITE_BASE_FOREGROUND=
# export GUM_WRITE_BASE_BACKGROUND=
export GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND=20
# export GUM_WRITE_CURSOR_LINE_NUMBER_BACKGROUND=
# export GUM_WRITE_CURSOR_LINE_FOREGROUND=
export GUM_WRITE_CURSOR_LINE_BACKGROUND=18
export GUM_WRITE_CURSOR_FOREGROUND=7
# export GUM_WRITE_CURSOR_BACKGROUND=
# export GUM_WRITE_END_OF_BUFFER_FOREGROUND=
# export GUM_WRITE_END_OF_BUFFER_BACKGROUND=
export GUM_WRITE_LINE_NUMBER_FOREGROUND=8
# export GUM_WRITE_LINE_NUMBER_BACKGROUND=
export GUM_WRITE_HEADER_FOREGROUND=$gum_color_header_fg
# export GUM_WRITE_HEADER_BACKGROUND=
export GUM_WRITE_PLACEHOLDER_FOREGROUND=8
# export GUM_WRITE_PLACEHOLDER_BACKGROUND=
export GUM_WRITE_PROMPT_FOREGROUND=3
# export GUM_WRITE_PROMPT_BACKGROUND=

# `gum table`
#
export GUM_TABLE_HEADER_BOLD=true
# export GUM_TABLE_BORDER_FOREGROUND=
# export GUM_TABLE_BORDER_BACKGROUND=
# export GUM_TABLE_CELL_FOREGROUND=
# export GUM_TABLE_CELL_BACKGROUND=
export GUM_TABLE_HEADER_FOREGROUND=$gum_color_header_fg
export GUM_TABLE_HEADER_BACKGROUND=18
export GUM_TABLE_SELECTED_FOREGROUND=15
export GUM_TABLE_SELECTED_BACKGROUND=19

# `gum spin`
#
export GUM_SPIN_SPINNER_FOREGROUND=$gum_color_selection
# export GUM_SPIN_SPINNER_BACKGROUND=
# export GUM_SPIN_TITLE_FOREGROUND=
# export GUM_SPIN_TITLE_BACKGROUND=

# `gum filter`
#
export GUM_FILTER_HEADER_BOLD=true
# export GUM_FILTER_INDICATOR_FOREGROUND=
# export GUM_FILTER_INDICATOR_BACKGROUND=
# export GUM_FILTER_SELECTED_PREFIX_FOREGROUND=
# export GUM_FILTER_SELECTED_PREFIX_BACKGROUND=
# export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND=
# export GUM_FILTER_UNSELECTED_PREFIX_BACKGROUND=
# export GUM_FILTER_HEADER_FOREGROUND=
# export GUM_FILTER_HEADER_BACKGROUND=
# export GUM_FILTER_TEXT_FOREGROUND=
# export GUM_FILTER_TEXT_BACKGROUND=
# export GUM_FILTER_CURSOR_TEXT_FOREGROUND=
# export GUM_FILTER_CURSOR_TEXT_BACKGROUND=
# export GUM_FILTER_MATCH_FOREGROUND=
# export GUM_FILTER_MATCH_BACKGROUND=
# export GUM_FILTER_PROMPT_FOREGROUND=
# export GUM_FILTER_PROMPT_BACKGROUND=
# export GUM_FILTER_PLACEHOLDER_FOREGROUND=
# export GUM_FILTER_PLACEHOLDER_BACKGROUND=

# `gum pager`
#
export GUM_FILTER_HEADER_BOLD=true
# export GUM_PAGER_FOREGROUND=
# export GUM_PAGER_BACKGROUND=
# export GUM_PAGER_LINE_NUMBER_FOREGROUND=
# export GUM_PAGER_LINE_NUMBER_BACKGROUND=
# export GUM_PAGER_MATCH_FOREGROUND=
# export GUM_PAGER_MATCH_BACKGROUND=
# export GUM_PAGER_MATCH_HIGH_FOREGROUND=
# export GUM_PAGER_MATCH_HIGH_BACKGROUND=
# export GUM_PAGER_HELP_FOREGROUND=
# export GUM_PAGER_HELP_BACKGROUND=
