## FZF (Fuzzy Finder) CONFIGURATION
export GREP_COLOR='1;37;41'
export FZF_COMPLETION_TRIGGER='~~'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden --follow --glob "!.git/*" --glob "!/keybase/*"'
export FZF_DEFAULT_OPTS='
  --no-mouse --margin=0,0,0,1
  --prompt="› "
  --tabstop=2
  -1
  --preview="[[ -d {} ]] && tree -L 1 {} || bat --style=numbers --color=always --line-range=:500 {}"
'
export FZF_CTRL_R_OPTS='--preview=""'

# Load init file generated by fzf install
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
