## FZF (Fuzzy Finder) CONFIGURATION
export GREP_COLOR='1;37;41'
export FZF_COMPLETION_TRIGGER='~~'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden --follow --glob "!.git/*" --glob "!/keybase/*"'
export FZF_DEFAULT_OPTS='
  --no-mouse --margin=0,0,0,1
  --prompt="› "
  --tabstop=2
  -1
  --preview="[[ -d {} ]] && tree -L 1 {} || bat --style=numbers --color=always --line-range=:500 {}"
'
export FZF_CTRL_R_OPTS='--preview=""'

# Load init file generated by fzf install
function _load_fzf() {
  if [[ -f ~/.fzf.zsh ]]; then
    source ~/.fzf.zsh
  elif [[ -f "$(brew --prefix fzf)/install" ]]; then
    "$(brew --prefix fzf)/install"
    _load_fzf
  fi
}

_load_fzf; unset _load_fzf

# FZF binds the fzf-cd-widget to Alt-C, but doesn't work in iTerm2 w/o further setup. Bind it to Ctrl-Y for now.
zle     -N            fzf-cd-widget
bindkey -M vicmd '^Y' fzf-cd-widget
bindkey -M viins '^Y' fzf-cd-widget
